# **In-depth with Rasterio**

## First, from [the Rasterio documentation](https://rasterio.readthedocs.io/en/stable/quickstart.html)

In [10]:
import numpy as np
import rasterio
from rasterio import Affine as A
from rasterio.warp import reproject, Resampling

In [11]:
with rasterio.Env():
    rows, cols = src_shape = (512, 512)

In [74]:
print(src_shape)
print(type(src_shape))

(512, 512)
<class 'tuple'>


In [13]:
rows

512

In [14]:
d = 1.0/240

In [15]:
d

0.004166666666666667

In [25]:
src_transform = A.translation(-cols*d/2, rows*d/2) * A.scale(d, -d)

In [26]:
src_transform

Affine(0.004166666666666667, 0.0, -1.0666666666666667,
       0.0, -0.004166666666666667, 1.0666666666666667)

In [75]:
rows*d/2

1.0666666666666667

In [78]:
src_transform * (0, 0)

(-1.0666666666666667, 1.0666666666666667)

In [79]:
src_transform * (1, 0)

(-1.0625, 1.0666666666666667)

In [81]:
src_transform * (0, 512)

(-1.0666666666666667, -1.0666666666666667)

In [77]:
src_transform * (512, 512)

(1.0666666666666667, -1.0666666666666667)

In [82]:
src_crs = {'init': 'EPSG:4326'}

In [83]:
src_crs

{'init': 'EPSG:4326'}

In [84]:
source = np.ones(src_shape, np.uint8) * 255

In [85]:
source

array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], dtype=uint8)

In [94]:
dst_shape = (1024, 1024)
dst_transform = A(425.0, 0.0, -237481.5, 0.0, -425.0, 237536.4)
dst_crs = {'init': 'EPSG:3857'}
destination = np.zeros(dst_shape, np.uint8)

In [95]:
dst_transform

Affine(425.0, 0.0, -237481.5,
       0.0, -425.0, 237536.4)

In [96]:
destination

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [97]:
reproject(
    source,
    destination,
    src_transform=src_transform,
    src_crs=src_crs,
    dst_transform=dst_transform,
    dst_crs=dst_crs,
    resampling=Resampling.nearest
)

In [98]:
destination

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [99]:
assert destination.any()

In [101]:
assert not destination.all()

In [102]:
destination.min()

0

In [103]:
destination.max()

255

In [104]:
type(destination)

numpy.ndarray

## Now let's try it ourselves
First we'll create the 3 band test image we created before.

In [106]:
b1 = np.arange(1, 21, dtype=np.uint8).reshape(4,5)
b2, b3 = b1 * 5, b1 * 10
raster = np.array([b1, b2, b3])

In [107]:
raster

array([[[  1,   2,   3,   4,   5],
        [  6,   7,   8,   9,  10],
        [ 11,  12,  13,  14,  15],
        [ 16,  17,  18,  19,  20]],

       [[  5,  10,  15,  20,  25],
        [ 30,  35,  40,  45,  50],
        [ 55,  60,  65,  70,  75],
        [ 80,  85,  90,  95, 100]],

       [[ 10,  20,  30,  40,  50],
        [ 60,  70,  80,  90, 100],
        [110, 120, 130, 140, 150],
        [160, 170, 180, 190, 200]]], dtype=uint8)

In [108]:
raster_resolution = d
raster_transform = A(d, 0, -97.911530, 0, -d, 29.890661)

In [109]:
raster_transform

Affine(0.004166666666666667, 0.0, -97.91153,
       0.0, -0.004166666666666667, 29.890661)